from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(850, 514)
        MainWindow.setMinimumSize(QtCore.QSize(850, 514))
        MainWindow.setMaximumSize(QtCore.QSize(850, 514))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 9, 781, 71))
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 90, 831, 211))
        self.groupBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(690, 40, 71, 21))
        self.label_2.setObjectName("label_2")
        self.textone = QtWidgets.QLineEdit(self.groupBox)
        self.textone.setGeometry(QtCore.QRect(540, 40, 141, 21))
        self.textone.setAlignment(QtCore.Qt.AlignCenter)
        self.textone.setObjectName("textone")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(440, 40, 91, 21))
        self.label_3.setObjectName("label_3")
        self.texttwo = QtWidgets.QLineEdit(self.groupBox)
        self.texttwo.setGeometry(QtCore.QRect(330, 40, 111, 20))
        self.texttwo.setAlignment(QtCore.Qt.AlignCenter)
        self.texttwo.setObjectName("texttwo")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(220, 40, 101, 21))
        self.label_4.setObjectName("label_4")
        self.textthree = QtWidgets.QLineEdit(self.groupBox)
        self.textthree.setGeometry(QtCore.QRect(110, 40, 111, 20))
        self.textthree.setAlignment(QtCore.Qt.AlignCenter)
        self.textthree.setObjectName("textthree")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(590, 100, 131, 21))
        self.label_5.setObjectName("label_5")
        self.textfour = QtWidgets.QLineEdit(self.groupBox)
        self.textfour.setGeometry(QtCore.QRect(460, 100, 113, 21))
        self.textfour.setAlignment(QtCore.Qt.AlignCenter)
        self.textfour.setObjectName("textfour")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(370, 100, 81, 21))
        self.label_6.setObjectName("label_6")
        self.textfive = QtWidgets.QLineEdit(self.groupBox)
        self.textfive.setGeometry(QtCore.QRect(260, 100, 111, 20))
        self.textfive.setAlignment(QtCore.Qt.AlignCenter)
        self.textfive.setObjectName("textfive")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(180, 100, 71, 21))
        self.label_7.setObjectName("label_7")
        self.textsix = QtWidgets.QLineEdit(self.groupBox)
        self.textsix.setGeometry(QtCore.QRect(70, 100, 111, 20))
        self.textsix.setAlignment(QtCore.Qt.AlignCenter)
        self.textsix.setObjectName("textsix")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(720, 160, 41, 21))
        self.label_8.setObjectName("label_8")
        self.textseven = QtWidgets.QLineEdit(self.groupBox)
        self.textseven.setGeometry(QtCore.QRect(590, 160, 121, 21))
        self.textseven.setAlignment(QtCore.Qt.AlignCenter)
        self.textseven.setObjectName("textseven")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(530, 160, 51, 21))
        self.label_9.setObjectName("label_9")
        self.texteight = QtWidgets.QLineEdit(self.groupBox)
        self.texteight.setGeometry(QtCore.QRect(420, 160, 111, 20))
        self.texteight.setAlignment(QtCore.Qt.AlignCenter)
        self.texteight.setObjectName("texteight")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(350, 160, 61, 21))
        self.label_10.setObjectName("label_10")
        self.textnine = QtWidgets.QLineEdit(self.groupBox)
        self.textnine.setGeometry(QtCore.QRect(240, 160, 111, 20))
        self.textnine.setAlignment(QtCore.Qt.AlignCenter)
        self.textnine.setObjectName("textnine")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(150, 160, 81, 21))
        self.label_11.setObjectName("label_11")
        self.textten = QtWidgets.QLineEdit(self.groupBox)
        self.textten.setGeometry(QtCore.QRect(40, 160, 111, 20))
        self.textten.setAlignment(QtCore.Qt.AlignCenter)
        self.textten.setObjectName("textten")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(150, 330, 551, 80))
        self.groupBox_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(436, 20, 101, 41))
        self.label_12.setObjectName("label_12")
        self.texteleven = QtWidgets.QLineEdit(self.groupBox_2)
        self.texteleven.setGeometry(QtCore.QRect(312, 30, 111, 21))
        self.texteleven.setObjectName("texteleven")
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setGeometry(QtCore.QRect(140, 20, 161, 41))
        self.label_13.setObjectName("label_13")
        self.texttwelve = QtWidgets.QLineEdit(self.groupBox_2)
        self.texttwelve.setGeometry(QtCore.QRect(20, 30, 111, 21))
        self.texttwelve.setObjectName("texttwelve")
        self.processbtn = QtWidgets.QPushButton(self.centralwidget)
        self.processbtn.setGeometry(QtCore.QRect(520, 430, 91, 31))
        self.processbtn.clicked.connect(self.do_the_math)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.processbtn.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.processbtn.setFont(font)
        self.processbtn.setObjectName("processbtn")
        self.cleardatabtn = QtWidgets.QPushButton(self.centralwidget)
        self.cleardatabtn.setGeometry(QtCore.QRect(230, 430, 91, 31))
        self.cleardatabtn.clicked.connect(self.cleardata)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.cleardatabtn.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.cleardatabtn.setFont(font)
        self.cleardatabtn.setObjectName("cleardatabtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 850, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "نرم افزار حسابداری سجاد"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ff0000;\">حسابداری ایران زمین</span></p></body></html>"))
        self.groupBox.setTitle(_translate("MainWindow", "دریافت اطلاعات"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">هزینه قطعات</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">تعداد نیروی کار</span></p><p align=\"center\"><br/></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:9pt;\">هزینه نیروی کار</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">تحقیق و توسعه و تست</span></p><p align=\"center\"><br/></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">تعداد خودرو</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">لجستیک</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">تبلیغات</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">مالیات</span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">ضایعات</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">سود(درصد)</span></p></body></html>"))
        self.groupBox_2.setTitle(_translate("MainWindow", "حساب نهایی"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">قیمت تمام شده</span></p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">قیمت نهایی با احتساب سود</span></p></body></html>"))
        self.processbtn.setText(_translate("MainWindow", "پردازش"))
        self.cleardatabtn.setText(_translate("MainWindow", "حذف داده"))
    def do_the_math(self):
        gataat = float(self.textone.text().replace(',', ''))
        tedade_neroy_kar, hazene_neroy_kar = (float(self.texttwo.text().replace(',', '')), float(self.textthree.text().replace(',', '')))
        tahgig_tosee_test = float(self.textfour.text().replace(',', ''))
        tedade_khodro, logestic, tabligat = (float(self.textfive.text().replace(',', '')), float(self.textsix.text().replace(',', '')), float(self.textseven.text().replace(',', '')))
        maliyat = float(self.texteight.text().replace(',', ''))
        zayeat = float(self.textnine.text().replace(',', ''))
        sod = int(self.textten.text().replace(',', ''))
        temp = gataat + (hazene_neroy_kar * tedade_neroy_kar) + tahgig_tosee_test + (logestic * tedade_khodro) + (tabligat * tedade_khodro) + maliyat + zayeat
        self.texteleven.setText("{:,.0f}".format(temp))
        self.texteleven.setAlignment(QtCore.Qt.AlignCenter)
        total = (temp * sod / 100) + temp
        self.texttwelve.setText("{:,.0f}".format(total))
        self.texttwelve.setAlignment(QtCore.Qt.AlignCenter)

    def cleardata(self):
        self.textone.setText('')
        self.texttwo.setText('')
        self.textthree.setText('')
        self.textfour.setText('')
        self.textfive.setText('')
        self.textsix.setText('')
        self.textseven.setText('')
        self.texteight.setText('')
        self.textnine.setText('')
        self.textten.setText('')
        self.texteleven.setText('')
        self.texttwelve.setText('')

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
